### ISSUE TITLE
Any progress?

### ISSUE THREAD

**Issue by manikantag** [marcphilipp/dbunit-datasetbuilder#7]
Hi, I find this interesting. Any further progress on this? Merging into DBUnit or Maven?

Also, I've see @opensource21 fork: https://github.com/opensource21/dbunit-datasetbuilder/ which is having somewhat new commits. Also, seems there are some API changes to be more of a DSL kind of feel.

Thanks.

**Comment by marcphilipp** [comment]
Thanks for your interest, @manikantag! The progress is (was) tracked in #6.

AFAIK the current state of affairs is that dbUnit has rejected the "merge request" of @opensource21. 

I have not since continued to work on publishing this as a separate Maven artifact.

I'm closing this issue. Let's use #6 for further discussion.

**Comment by opensource21** [comment]
@manikantag You can get the jar if you add the following repository

```
   <repositories>
     <repository>
        <id>opensource21</id>
        <url> http://opensource21.github.com/releases</url>
      </repository>
  </repositories>

```

**Comment by manikantag** [comment]
@opensource21 I don't see any 'releases' repo in your GitHub account. Will that work?

**Comment by opensource21** [comment]
@manikantag At https://github.com/opensource21/sze/blob/develop/pom.xml you can see it in action and it works fine. You can see the release at https://github.com/opensource21/opensource21.github.com

**Comment by manikantag** [comment]
I see that. Thanks.
